### ISSUE TITLE
EEPROM.h: No such file or directory

### ISSUE THREAD

**Issue by inesMatellano** [jgromes/RadioLib#1023]
Good morning,
I'm trying to use the library for my Arduino Nano RP2040 and RFM95, but when I try to run it, it says: fatal error: EEPROM.h: No such file or directory #include <EEPROM.h>.
In the documentation, it stated that the library was compatible with the system. My question is, do I need to make any modifications to the library or create an EEPROM.h emulator?
PD: Sorry if this question has already been answered, I couldn't find it.

**Sketch that is causing the module fail**
fatal error: EEPROM.h

**Additional info (please complete):**
 - MCU: RP2040
 - Link to Arduino core:(https://github.com/arduino/ArduinoCore-mbed)
 - Wireless module type SX1276
 - Arduino IDE version 2.3.2
 - Library version 6.4.2

**Comment by jgromes** [comment]
This was caused by EEPROM being required for LoRaWAN. That is no longer the case after recent changes (mainly #1017) that will be released in 6.5.0 update. In the meantime, you can use the current master.

However, there is also an alterantive RP2040 Arduino core that does include EEPROM library: https://github.com/earlephilhower/arduino-pico

**Comment by inesMatellano** [comment]
Thank you for the response! I have found that there is a definition called RADIOLIB_EEPROM_UNSUPPORTED. Can I use this definition to create a LoRaWAN OTAA?

**Comment by inesMatellano** [comment]
Thanks! i will wait for the update

**Comment by HeadBoffin** [comment]
Note to @HeadBoffin, do persistence for RP2040

**Comment by StevenCellist** [comment]
Moved to https://github.com/radiolib-org/radiolib-persistence/issues/2
