### ISSUE TITLE
STM8 Arduino

### ISSUE THREAD

**Issue by k0derAl** [jgromes/RadioLib#1113]
Hello
WIll project work with STM8-Arduino in the feature?

**Comment by jgromes** [comment]
STM8 Arduino core has been archived last year (https://github.com/stm32duino/Arduino_Core_STM8). Out of curiousity, I tried to compile the library but the compiler stared asking for a license which I requested via email and it never arrived.

So to answer your question, RadioLib might work with STM8 (and feel free to try) since it's mostly platform-agnostic. However, I cannot verify this and would suggest against using an outdated, unmaintained platform for a low-end 8-bit microcontroller in a world where you can get 32-bit ARM Cortex MCUs for literal pennies.

**Comment by k0derAl** [comment]
thank you
