### ISSUE TITLE
Request for Robot36 and Robot72 in SSTV

### ISSUE THREAD

**Issue by Panger95** [jgromes/RadioLib#1160]
I would like to be able to use the Robot Modes while transmitting in SSTV.

**Comment by jgromes** [comment]
I think the reason I originally did not include these modes is that they use YCbCr color as opposed to RGB, and also because of their asymmetric timing. Especially Robot36, which averages the Cb/Cr components over two lines, which is not really compatible with RadioLib one-line-at-a-time approach.

That being said, I was able to add some support for it and it seems to be working. Fair warning, I'm not doing the above-mentioned averaging, which leads to the colors being slightly off. However, the image is still pretty clear: see below, Robot36 sent via SX1278.

![202407131351](https://github.com/user-attachments/assets/59418eaf-f87c-418e-a4ad-832e0dc2bc66)

**Comment by Panger95** [comment]
Do you remember which filter bandwidth, if it was USB, Narrow FM, or LSB.
Also which software did you use to decode it? Did you use QSSTV?

**Comment by jgromes** [comment]
I used the SSTV in AFSK mode, so FM - I don't recall whether it was narrow or wide but either one should work. For decoding I used MMSSTV.
