### ISSUE TITLE
Problem at compiling transmit/recieve example sketches for Arduino Pro Mini 3.3V 8MHz

### ISSUE THREAD

**Issue by DRK970** [jgromes/RadioLib#216]
![ErrorArduino](https://user-images.githubusercontent.com/56574447/102676052-6827bd00-4161-11eb-8f3d-3080f6beceba.JPG)

I tried to add #include<Arduino.h>in Module.h and Module.cpp, it didn't work either.

It compiles only for the 5V 16MHz Atmega328P uC.

**Comment by jgromes** [comment]
Not sure if this is still as an issue as it was closed soon after opening, but since it's all linker errors, I'd start by checking if there's multiple RadioLib versions installed. It also looks like you have installed the library to the Arduino install directory - you'll lose it if you update your Arduino version. Libraries should be installed into sketchbook libraries folder, or better yet, with Arduino library manager.
