### ISSUE TITLE
How can I get the raw data on DIO2 with interrupt ?

### ISSUE THREAD

**Issue by AjJordy** [jgromes/RadioLib#22]
I'm using a ESP32 and a RFM69. I saw something about use the receiveDirect() for this. But I dont know how to use. When I try to see the DIO1 there is the clock (I guess). But in the DIO2 there is noise. 

My goal is capture the signal of a RF garage control or similar devices.

**Comment by jgromes** [comment]
Reading the raw data is not supported by the library and I'm not planning on adding it in the near future. Reasoning behind that is this feature probably wouldn't be used by many people.
 
The only thing receiveDirect() does is it puts the radio into direct reception mode, so that DIO1 and DIO2 act as serial clock and data output. I have never checked the output to be honest - I never had a use for the serial data stream.

**Comment by giordand** [comment]
@AjJordy , could you find any solution to this? I'm trying to do exactly the same thing. I have an sx1278 and a 434 mhz radio control

**Comment by AjJordy** [comment]
I'm using this [https://github.com/rrobinet/RFM69X_Library](Repo)

**Comment by AjJordy** [comment]
I'm using this [https://github.com/rrobinet/RFM69X_Library](repo)

**Comment by giordand** [comment]
Ok, but I'm using a Mini SX1278 LoRa Transceiver Module

**Comment by AjJordy** [comment]
Looking for something like Continuous Mode, Promiscuous Mode. In my case, I needed to configure by SPI each register.

**Comment by giordand** [comment]
Yes, I did that and I can see that raw data changes when i press the button of my control, but i don't now how to save that signal in order to send it again
