### ISSUE TITLE
No two way communication

### ISSUE THREAD

**Issue by prerak9** [jgromes/RadioLib#322]
Hello,
I am not able to establish two way communication. Please help me with a sample code or any relevant info.
Thank You

**Comment by jgromes** [comment]
This issue is lacking almost all relevant information - no really, from the title and description I can tell absolutely nothing about your problem.

Which radio module are you using?
Which Arduino board?
Which Arduino core?
Did you try the examples? If so, what was the result? If not, what is the code that you're running?
Is there an error code?

Try running the example codes, they should be tested and give you a general idea on how to use the library. Only then try to implement whatever it is that you're trying to accomplish.

I'm going to close and lock this issue now. Please only open issues if you have a specific problem that you need help with - note that if your issue doesn't match any issue template, maybe it would be better as a discussion.
