### ISSUE TITLE
Setting power seems to wrong on SX1278

### ISSUE THREAD

**Issue by sh123** [jgromes/RadioLib#385]
When setting power on SX1278 to 2 dBm, I'm receiving signal at -30 dBm from another device on the table, when setting to 1 dBm, receiving at -96 dBm, clearly the difference is not 1 dB.

**Comment by jgromes** [comment]
There was an issue in the way RF output pin was selected. SX1278 has two possible RF outputs:

* RFO, which is suitable for power levels -3 to 15 dBm
* PA_BOOST for power levels 2 to 17 dBm, with optional 20 dBm output.

It seems that nearly all SX178 modules on the market are using PA_BOOST only, leaving RFO floating. The issue was that at the 1 dBm level, the library switched to RFO which is most likely disconnected on your module. That's the reason for the massive drop in RSSI.

I extended the `setOutputPower` method to allow RFO/PA_BOOST selection, defaulting to PA_BOOST. This means that the lowest power level achievable on PA_BOOST is now required to be +2 dBm.

Fixed in the latest commit, thanks for reporting!
