### ISSUE TITLE
LLCC68 and UART support

### ISSUE THREAD

**Issue by 1sa4c** [jgromes/RadioLib#565]
**Description.**
Is the LLCC68 supported? The github page says it is, but the [GithubIO page](https://jgromes.github.io/RadioLib/) doesn't list it under supported modules. If it really is, would it be possible to have an example code for it? If not, are there any plans for implementing it?

Also, I'm a bit confused with UART support. Would i be able to use RadioLib for a LLCC68 with UART module?

Thanks.

**Comment by jgromes** [comment]
LLCC68 is supported - using it is nearly the same as any SX126x module, since that's all that it really is, a SX1268 with some limitations on the supported spreading factor etc. That's why there are no examples for it, just replace the class name in SX126x examples and it should work.

Regarding UART, that is not supported, because RadioLib is intended to be used when directly connected to the radio module via SPI. The LLCC68 itself does not have a UART interface. Some manufacturers however add their own microcontroller to it which implements this interface, usually in a very limited way.
