### ISSUE TITLE
RADIOLIB_GENERATE_CALLBACK hides Module::_spi in GODMODE

### ISSUE THREAD

**Issue by ryanrsrs** [jgromes/RadioLib#605]
I can't access Module::_spi from a derived class because it is private, even when RADIOLIB_GODMODE is defined.

This occurs because in Module.h, the RADIOLIB_GENERATE_CALLBACK macros screw with private/public access specifiers of following members in a way that ignores RADIOLIB_GODMODE.

There are several ways to fix this, not sure which is best:
a) Make the callback macros GODMODE-aware.
b) Move the macro calls to the end of the Module class (e.g. after _cs, _spiSettings, etc).
c) Change Module.h:432 to a #if/#else:
#if !defined(RADIOLIB_GODMODE)
  private:
#else
  public:
#endif

**Comment by jgromes** [comment]
I think the first solution is definitely the cleanest, since in godmode, the callback function itself should be accessible from outside. Hoever, the macro is convloted as it is, without an additional condition, so I'm going to just move it to the end and hope that no one ever needs to access the callback function pointers from outside of Module class.
