### ISSUE TITLE
Minimize config for specific module

### ISSUE THREAD

**Issue by garudaonekh** [jgromes/RadioLib#636]
Hi,
I want to LLCC68 for Atmega16, which has only 16KB space. It's too small for RadioLib.

Anyway to configure it for minimal size for specific LORA module only(LLCC68)?

Thanks;

**Comment by jgromes** [comment]
I suppose this depends on what do you want to do with RadioLib. "Only" LLCC68 module means that you also need the `SX1268`, `SX126x`, `Module` and `PhysicalLayer` classes due to inheritances. Sou you could try removing functionality you don't need - and hope that you can do better job of it than the compiler. You could also try to optimize the compiler for size (if it's not already).

This is not really an issue (as it doesn't need an action from RadioLib), so I'm converting to discussion instead.
