### ISSUE TITLE
Playing with SX1280

### ISSUE THREAD

**Issue by lw2dtz** [jgromes/RadioLib#656]
I started working with the SX1280 and an arduino 8 MHZ internal crystal,in 2.4Ghz. The examples work perfect, but when I want to use it with the MORSE example, I have to change the line to:

int state = radio.beginGFSK();

for the IDE 1.8.13 to compile it. Once loaded it reports:

[SX1280] Initializing ... failed, code -705

TIA

Gustavo.

**Comment by jgromes** [comment]
You have to use the `beginGFSK()` method since the default `begin()` method initializes the LoRa modem, whereas the GFSK modem is needed for Morse.

To get some more information however, please fill in the rest of the issue template. Mainly the output from [debug mode](https://github.com/jgromes/RadioLib/wiki/Debug-mode) (although the other points such as the wiring are important as well).

**Comment by lw2dtz** [comment]
I found the error in the configuration of the pins.
 Runs OK.

![20230112_214059 1](https://user-images.githubusercontent.com/6095237/212337931-120424d9-1c71-42f7-b907-57e693349f14.jpg)

 Thanks.

**Comment by jgromes** [comment]
Glad you were able to fix it!
