### ISSUE TITLE
radio.invertIQ  --  not working as expected for sx1278 module

### ISSUE THREAD

**Issue by K4KDR** [jgromes/RadioLib#778]
Good day!   I don't know when my ability to successfully TRANSMIT stopped working, since my primary use of LoRa devices is in RECEIVE mode.

`Environment:   Using RadioLib v6.0.0 in the Arduino IDE w/ an UNO + sx1278 LoRa shield`

But with a request to attempt to rescue a non-communicating satellite, it was time to use my transmit functionality.  While I was **physically** transmitting (as evidenced by observing an SDR waterfall set to the RF frequency), there was **no decode** of the LoRa payload bytes using a second sx1278 running the same sketch.

Fortunately, when using a **tinyGS ESP32 LoRa device** to transmit, my sx1278 Arduino-based devices confirmed that the correct bytes were being transmitted over-the-air, so I was not completely without a means to transmit.   However, as you can imagine I was anxious to get to the bottom of my Arduino TX situation.  

After an entire day of trial & error, I believe that I've finally located the cause.  Since your example PingPong and other TX/RX sketches worked perfectly, I knew there was not a hardware issue.  So, I've been testing & verifying every LoRa parameter and syntax in my sketch until I could successfully transmit (and decode) again using the sx1278 modules. (I should add that in the past, these sketches DID transmit properly, so it was just a matter of finding what had changed)

The final result (very sorry for the long introduction, but I didn't know how else to explain my situation) is that I had to use **INVERTED I/Q** to transmit even though my RX devices (both Arduino sx1278 -and- tinyGS ESP32) were using NON-inverted IQ.

Here is a test between two sx1278 devices showing the situation:

![invertIQ-issue](https://github.com/jgromes/RadioLib/assets/19886368/bd7a0a5a-0f1e-43ce-8c4e-dd48df72d211)

... and for confirmation, a tinyGS ESP32 also decoding the test transmission of two 'FF FF' bytes:

![ESP32-RX_inverted_TX_only](https://github.com/jgromes/RadioLib/assets/19886368/a6ed6288-303b-4236-9dbb-1c9e7fdd71a3)

... upon researching the issue to try to determine if I was doing something incorrectly, I found a difference in how the RadioLib code spells out the use of the **radio.invertIQ** command for SX127x devices (noticed this in both **.h** and **.cpp** files):

![radiolib-invertIQ-files](https://github.com/jgromes/RadioLib/assets/19886368/e5f37f7b-603a-415a-9d08-6e7440fadd6b)

... is this perhaps why I have to artificially invert my sx1278 transmitter sketch to make the payload be decoded by non-inverted devices?

MANY thanks in advance and please let me know if I can clarify anything, provide more info, or assist in any way!

-Scott,  K4KDR

**Comment by jgromes** [comment]
This was an interesting one - I was able to confirm that there is indeed something wrong with the IQ inversion - when explicitly setting both ends to the same inversion (both enabled or both disabled), it was not working. Like you said, the link can only be established when the ends are opposite (Tx inverted, Rx non-inverted or vice versa).

The strange thing was that using default examples (without any calls to invertIQ, after power cycle to get rid of any register changes), things were working correctly. This lead me to believe that something in invertIQ was not working, so I took a couple SDR recordings:

![Screenshot_52](https://github.com/jgromes/RadioLib/assets/3407192/caa193e0-f352-4f11-9151-fd07b891146c)

The first one is with inversion explicitly set to false, the secod one to true and the final one with the default configuration. What strikes me as odd is that the default one seems to match the result of `invertIQ(true)`, which is not what I would expect. As far as I can tell, RadioLib **should** be configuring IQ inversion in accordance with the latest datasheet revision.

Going off of the default preamble using upchirps, I'm guessing that upchirps = non-inverted IQ. The SX127x allows for separate IQ configuration on the Rx and Tx paths, so I swapped the Tx path inversion in RadioLib (because previously invertIQ(false) created downchirps). However, this implies an issue in the datasheet.

**Comment by jgromes** [comment]
I also posted on the LoRa developer forum to get some feedback: https://forum.lora-developers.semtech.com/t/sx1276-invertiq-tx-path-swapped/1651

**Comment by K4KDR** [comment]
Thanks so much for checking on that!!    So for the moment I should just continue to use invertIQ=true as a work-around for a TX device?     Or have you made a change - and I should update RadioLib?    Just wanted to make sure I understood where things stand as of right now.   Thanks!

**Comment by jgromes** [comment]
I've made the change in RadioLib, so that from user perspective, it looks like it's working correctly. You will have to update to the latest commmit (version 6.1.0 should be coming in about a week).
