### ISSUE TITLE
Allow use of low power PA for SX1262/SX1268, perhaps SX1261

### ISSUE THREAD

**Issue by S5NC** [jgromes/RadioLib#880]
See _13.4.4 SetTxParams_ in the SX1261/2 and SX1268 datasheet.
Use case: The SX1262's low power PA is assumed to have less noise than the higher power PA. A 9 dBm input is needed to reach the P1dB of an external PA. 9 dBm can be provided via the SX1262's high or low power PA, in this case it is best to provide it via the low power PA.

> The output power is defined as power in dBm in a range of
• - 17 (0xEF) to +14 (0x0E) dBm by step of 1 dB if low power PA is selected
• - 9 (0xF7) to +22 (0x16) dBm by step of 1 dB if high power PA is selected

**Comment by jgromes** [comment]
Let's take a look at the relevant datasheet sections (taken from DS.SX1261-2.W.APP, Rev. 1.2):

![Screenshot_74](https://github.com/jgromes/RadioLib/assets/3407192/d842b789-55a5-4752-9d75-618b388ef615)

This references the SetPaConfig command:

![Screenshot_75](https://github.com/jgromes/RadioLib/assets/3407192/052948c4-7982-4992-a845-bae0d5bcd52a)

The description of that command claims that `deviceSel` should be used to selected between the SX1261 and SX1262 devices. So, does SX1262 really implement both a low power and a high power PA? I was not able to find that information in the datasheet.

**Comment by jgromes** [comment]
Honestly, I was always confused about the SX126x power configuration, there's just way too many magic parameters for me to like. I think that the reference about hpMax is just because the PA is different, though I never got too deep into that. And you are right, that is me from one year ago.

I think at some point the Semtech support guys mentioned a new release for the datasheet with some more information about previously undocumented features, so we'll see.
